### ISSUE TITLE
эту парашу надо переписать полностью

### ISSUE THREAD

**Issue by Boobl1k** [Boobl1k/Messenger.NET#4]
эту парашу надо переписать полностью

по хорошему надо разбить основное приложение на слои и оттуда использовать сервисы тут
и сам врайтер переименовать и переделать в asp.net бэкенд с бэкграунд сервисами

_Originally posted by @Boobl1k in https://github.com/Boobl1k/Messenger.NET/pull/3#discussion_r1031443326_

**Comment by Focus1337** [comment]
Done
